version: "3.7"

services:
    db:
        container_name: mysql
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password123
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
